export default [
  {
    title: 'Pediatric Dentistry of Palo Alto',
    stars: 5.0,
    image: 'https://i.ibb.co/cXF2rrc/dentist.png',
    cta: 'See Reviews',
    labels: ['ASD Specialist', 'Insurance Accepted'],
    type: 'Dentist',
    latitude: 37.423470, 
    longitude: -122.197740,
  },
  {
    title: 'Magical Bridge Playground',
    stars: 4.5,
    image: 'https://i.ibb.co/LpBDMPr/playground.png',
    cta: 'See Reviews',
    labels: ['Play', 'Fun for kids', 'Free', 'Social'],
    latitude: 37.416230,
    longitude: -122.103370,
    type: 'After School',
  },
  {
    title: 'PlaySteps for Developing Kids',
    stars: 4.6,
    image: 'https://i.ibb.co/Y36Tc25/playsteps.png',
    cta: 'See Reviews',
    labels: ['Accessible', 'OT'],
    latitude: 37.460730,
    longitude: -122.179450,
    type: 'Occupational Therapy',
  },
  // {
  //   title: 'Bistro Maxine',
  //   stars: 3.5,
  //   image: 'https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1326&q=80',
  //   cta: 'See Reviews',
  //   labels: ['Low Noise'],
  //   latitude: 37.444600,
  //   longitude: -122.161390,
  //   type: 'Restaurant',
  // },
  {
    title: 'Childrens Health Council',
    stars: 5.0,
    image: 'https://i.ibb.co/pXKVwhK/chc.png',
    cta: 'See Reviews',
    labels: ['Medical','Community'],
    latitude: 37.440290,
    longitude: -122.178740,
    type: 'Psychologist',
  },
  {
    title: 'Dr. Lisa Talbott, PHD',
    stars: 4.7,
    image: 'https://i.ibb.co/X481MbZ/lisa.png',
    cta: 'See Reviews',
    labels: ['Cognitive Behavioral Therapy'],
    latitude: 37.448970,
    longitude: -122.156450,
    type: 'Psychologist',
  },
  {
    title: 'Community School of Music & Art',
    stars: 4.2,
    image: 'https://i.ibb.co/DVXKFZG/comm-School.png',
    cta: 'See Reviews',
    labels: ['Music', 'After School'],
    latitude: 37.4074286,
    longitude: -122.110909,
    type: 'Music Therapy',
  },
];